### PR TITLE
New Clarity Test Generation Script For Extensive Testing

### PR DESCRIPTION
**Pull request by setzeus**
Very much still a draft / wip meant to merge & lay down two different approaches for updating the sbtc-mini testing suite. These were specifically needed to accommodate the life-cycle methods found in sbtc-stacking-pool.clar.

### CODE REVIEW

**Comment by AshtonStephens** [comment]
Hate to be that guy, but can you fix the code factor complaints?

**Comment by setzeus** [comment]
Closing due to duplicate / progress on #613

**Comment by sergey-shandar** [comment]
@setzeus do you still need the branch?

**Comment by setzeus** [comment]
Negative. Can delete.

**Pull request closed without merging**
