### PR TITLE
545 sbtc alpha invalid schnorr signature error

### PR DESCRIPTION
**Pull request by jferrant**
We were not actually using the prevouts to sign the transaction. Fixed now. :D Kudos Joey 

see broadcast signed BTC transaction: https://mempool.space/testnet/tx/83c0e4aa594cdb65c3cf2136cf634e346528396e1070d32a44eb8e0d2e672516

### CODE REVIEW

**Review by xoloki — APPROVED** [review]
LGTM, thanks for working through this with me!

**Comment by jferrant** [comment]
> LGTM, thanks for working through this with me!

Thanks to you too! :D Good catch on the prevouts

**Review by netrome — APPROVED** [review]
Nice!

**Review by stjepangolemac — APPROVED** [review]

**Comment by netrome** [comment]
Great stuff! I'll merge this now, and try it out in the VM with @stjepangolemac

**Pull request merged**
