### PR TITLE
Add documentation and clarification to clarity-bitcoin

### PR DESCRIPTION
**Pull request by friedger**
This PR
* adds documentation to the bitcoin library
* replaces state-res with result and uses `(state (unwrap! result result)` instead of `match`
* adds a function `bool-list-of-len` to generate a list of true values
* uses stacks items instead of elements in describing stack items of witness data
* slices the iterator to the tree-depth
* removes `was-wtx-mined-internal`

### CODE REVIEW

**Comment by friedger** [comment]
Unit tests fail in this repo but pass in https://github.com/friedger/clarity-bitcoin/pull/14

**Comment by jo-tm** [comment]
please send a PR for the good branch @friedger

**Comment by friedger** [comment]
I would like to use the same code in both repos (or link them or something like that) so that we have one version of the bitcoin library. I don't have a good idea how to do that.

**Comment by friedger** [comment]
@FriendsFerdinand Thank you for fixing this! It would have taken me ages to solve it.

**Review by FriendsFerdinand — APPROVED** [review]

**Review by MarvinJanssen — APPROVED** [review]
LGTM. We can optimise the lib later.

**Pull request merged**
