### PR TITLE
Fix test-was-wtx-mined-internal-5

### LINKED ISSUE #507: [sbtc-mini] test-was-wtx-mined-internal-5 uses wrong data
**Describe the bug**
test-was-wtx-mined-internal-5 uses wrong data for coinbase tx, header hash, etc.

**To Reproduce**
change bitcoin library so that was-tx-mined returns the txid and see that the test does not pass due to wrong data.

**Additional context**
https://github.com/friedger/clarity-bitcoin/commit/f641367ed163b8b9e3603ec9ae5078ad80824e33

### PR DESCRIPTION
**Pull request by friedger**
This PR
* corrects the wrong data for test-was-wtx-mined-internal-5
* fixes #507

### CODE REVIEW

**Review by jo-tm — APPROVED** [review]

**Comment by jo-tm** [comment]
@FriendsFerdinand can you review this bug/fix this week or give ETA? thanks.

**Comment by friedger** [comment]
I have added more docs and clarifications in my repo. Shall I send a PR?

**Comment by jo-tm** [comment]
@friedger please send a PR.

**Review by FriendsFerdinand — APPROVED** [review]

**Review by MarvinJanssen — APPROVED** [review]

**Comment by friedger** [comment]
@jo-tm Here is the PR: https://github.com/Trust-Machines/stacks-sbtc/pull/516

**Pull request merged**
