### PR TITLE
Basic Hand-off Unit Tests

### PR DESCRIPTION
**Pull request by jo-tm**
- `hand-off-fulfillment-pool-not-found`

### CODE REVIEW

**Comment by jo-tm** [comment]
@friedger do you know why this Hand-off test is breaking 2 other stacking pool tests? I break the context/fixture?

```javascript
 ERRORS 

test-sign-pre-register-with-expired-allowance-in-future: user can pre-register only when allowance does expire in the future => https://deno.land/x/clarinet@v1.7.0/index.ts:278:10
error: Error: Expected ok, got (err u6042)
    throw new Error(
          ^
    at consume (https://deno.land/x/clarinet@v1.7.0/index.ts:457:11)
    at String.expectOk (https://deno.land/x/clarinet@v1.7.0/index.ts:470:10)
    at file:///Users/joseignacio/Documents/GitHub/core-eng/sbtc-mini/.test/sbtc-stacking-pool_allow_flow_test.ts:38:44
    at Array.map (<anonymous>)
    at Object.fn (file:///Users/joseignacio/Documents/GitHub/core-eng/sbtc-mini/.test/sbtc-stacking-pool_allow_flow_test.ts:38:19)
    at fn (https://deno.land/x/clarinet@v1.7.0/index.ts:320:23)

test-pox-3-cycle-length: check cycle length => https://deno.land/x/clarinet@v1.7.0/index.ts:278:10
error: Error: Expected ok, got (err u3702)
    throw new Error(
          ^
    at consume (https://deno.land/x/clarinet@v1.7.0/index.ts:457:11)
    at String.expectOk (https://deno.land/x/clarinet@v1.7.0/index.ts:470:10)
    at file:///Users/joseignacio/Documents/GitHub/core-eng/sbtc-mini/.test/sbtc-stacking-pool_test.ts:31:43
    at Array.map (<anonymous>)
    at Object.fn (file:///Users/joseignacio/Documents/GitHub/core-eng/sbtc-mini/.test/sbtc-stacking-pool_test.ts:31:18)
    at fn (https://deno.land/x/clarinet@v1.7.0/index.ts:320:23)

 FAILURES 

test-sign-pre-register-with-expired-allowance-in-future: user can pre-register only when allowance does expire in the future => https://deno.land/x/clarinet@v1.7.0/index.ts:278:10
test-pox-3-cycle-length: check cycle length => https://deno.land/x/clarinet@v1.7.0/index.ts:278:10
```

**Comment by friedger** [comment]
@jo-tm There is an extra block when deploying more contracts, therefore some block heights are wrong. 3701 => 3702

**Comment by jo-tm** [comment]
@friedger gotcha, will check where are those numbers.

**Review by friedger — APPROVED** [review]
LGTM

**Pull request merged**
