### PR TITLE
Update error codes

### LINKED ISSUE #618: make error codes unique across contracts
**Describe the feature**
As defined in https://docs.google.com/spreadsheets/d/1udTG-fkyvj6bDZhN6NKYedYxBlV1Ycftqu9eM3_rHeA/edit#gid=0 all error codes should be unique across sbtc contracts. The error codes should use the defined code spaces.

### PR DESCRIPTION
**Pull request by friedger**
This PR
* fixes #618 
* replaces error codes with 4 digit codes using specific following format:

Component | Code | Description
-- | -- | --
Controller | 1XXX | Errors related to the controller and upgrades.
Registry | 2XXX | Errors coming directly from the registry.
Token | 3XXX | Errors coming directly from the token.
Deposit | 4XXX | Errors related to making and processing BTC deposits.
Redemption | 5XXX | Errors related to redeeming sBTC for BTC.
Pool | 6XXX | Errors related to the sBTC stacking pool.
Hand-off | 7XXX | Errors related to the peg hand-off process.
Bitcoin library | 8XXX | Errors coming directly from the Bitcoin library / helper.
Debug | 9XXX | Debugging related errors.

* does not update bitcoin library to make merging #516 easier

### CODE REVIEW

**Comment by MarvinJanssen** [comment]
I think we should renumber all of them from the start of the error space.

**Comment by MarvinJanssen** [comment]
I merged this branch into #605 and ran the script.

See the result: https://github.com/Trust-Machines/stacks-sbtc/blob/89b7d7eec42af8b9d95de6dfe3460bd5c9abc0b3/sbtc-mini/README.md

**Comment by friedger** [comment]
The table is nice and gives a good overview. Now we can improve the numbers in the next PR

**Comment by MarvinJanssen** [comment]
Closing this PR because the changes have been merged into #605.

**Pull request closed without merging**
